language: node_js

node_js:
  - "16.6.1"

env:
  - DATABASE_URL=postgresql://localhost:5432/taxi_trips

before_script:
  - psql -c 'create database taxi_trips;' -U postgres
  - psql -U postgres -d taxi_trips -a -f tables.sql
  - psql -U postgres -d taxi_trips -a -f data.sql

services: 
  - postgresql